/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as LoginRouteImport } from './routes/login';
import { Route as AuthenticatedRouteImport } from './routes/_authenticated';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard';
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar';
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics';
import { Route as AuthenticatedVisitsIndexRouteImport } from './routes/_authenticated/visits/index';
import { Route as AuthenticatedVisitsVisitIdRouteImport } from './routes/_authenticated/visits/$visitId';
import { Route as AuthenticatedAdminCatalogsRouteImport } from './routes/_authenticated/admin/catalogs';

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedVisitsIndexRoute =
  AuthenticatedVisitsIndexRouteImport.update({
    id: '/visits/',
    path: '/visits/',
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedVisitsVisitIdRoute =
  AuthenticatedVisitsVisitIdRouteImport.update({
    id: '/visits/$visitId',
    path: '/visits/$visitId',
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedAdminCatalogsRoute =
  AuthenticatedAdminCatalogsRouteImport.update({
    id: '/admin/catalogs',
    path: '/admin/catalogs',
    getParentRoute: () => AuthenticatedRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/login': typeof LoginRoute;
  '/analytics': typeof AuthenticatedAnalyticsRoute;
  '/calendar': typeof AuthenticatedCalendarRoute;
  '/dashboard': typeof AuthenticatedDashboardRoute;
  '/admin/catalogs': typeof AuthenticatedAdminCatalogsRoute;
  '/visits/$visitId': typeof AuthenticatedVisitsVisitIdRoute;
  '/visits/': typeof AuthenticatedVisitsIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/login': typeof LoginRoute;
  '/analytics': typeof AuthenticatedAnalyticsRoute;
  '/calendar': typeof AuthenticatedCalendarRoute;
  '/dashboard': typeof AuthenticatedDashboardRoute;
  '/admin/catalogs': typeof AuthenticatedAdminCatalogsRoute;
  '/visits/$visitId': typeof AuthenticatedVisitsVisitIdRoute;
  '/visits': typeof AuthenticatedVisitsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_authenticated': typeof AuthenticatedRouteWithChildren;
  '/login': typeof LoginRoute;
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute;
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute;
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute;
  '/_authenticated/admin/catalogs': typeof AuthenticatedAdminCatalogsRoute;
  '/_authenticated/visits/$visitId': typeof AuthenticatedVisitsVisitIdRoute;
  '/_authenticated/visits/': typeof AuthenticatedVisitsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/calendar'
    | '/dashboard'
    | '/admin/catalogs'
    | '/visits/$visitId'
    | '/visits/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/calendar'
    | '/dashboard'
    | '/admin/catalogs'
    | '/visits/$visitId'
    | '/visits';
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/analytics'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/catalogs'
    | '/_authenticated/visits/$visitId'
    | '/_authenticated/visits/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated': {
      id: '/_authenticated';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar';
      path: '/calendar';
      fullPath: '/calendar';
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics';
      path: '/analytics';
      fullPath: '/analytics';
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/visits/': {
      id: '/_authenticated/visits/';
      path: '/visits';
      fullPath: '/visits/';
      preLoaderRoute: typeof AuthenticatedVisitsIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/visits/$visitId': {
      id: '/_authenticated/visits/$visitId';
      path: '/visits/$visitId';
      fullPath: '/visits/$visitId';
      preLoaderRoute: typeof AuthenticatedVisitsVisitIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/admin/catalogs': {
      id: '/_authenticated/admin/catalogs';
      path: '/admin/catalogs';
      fullPath: '/admin/catalogs';
      preLoaderRoute: typeof AuthenticatedAdminCatalogsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute;
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute;
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute;
  AuthenticatedAdminCatalogsRoute: typeof AuthenticatedAdminCatalogsRoute;
  AuthenticatedVisitsVisitIdRoute: typeof AuthenticatedVisitsVisitIdRoute;
  AuthenticatedVisitsIndexRoute: typeof AuthenticatedVisitsIndexRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminCatalogsRoute: AuthenticatedAdminCatalogsRoute,
  AuthenticatedVisitsVisitIdRoute: AuthenticatedVisitsVisitIdRoute,
  AuthenticatedVisitsIndexRoute: AuthenticatedVisitsIndexRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
